<a href="https://colab.research.google.com/github/nahumsa/DM-Reconstruction/blob/Tensorflow_test/Trace%20Distance%20Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
print(tf.__version__)

2.2.0-rc2


# Tests

In [0]:
#Creating pauli matrices
sigma_0_np = np.array([[1.,0.],
                      [0.,1.]], dtype=np.complex64)

sigma_1_np = np.array([[0.,1.],
                       [1.,0.]], dtype=np.complex64)

sigma_2_np = np.array([[0.,1.j],
                       [-1.j,0.]], dtype=np.complex64)

sigma_3_np = np.array([[1.,0.],
                       [0.,-1.]], dtype=np.complex64)

#Converting to tensors
sigma_0 = tf.Variable(sigma_0_np, tf.complex64)

sigma_1 = tf.Variable(sigma_1_np, tf.complex64)

sigma_2 = tf.Variable(sigma_2_np, tf.complex64)

sigma_3 = tf.Variable(sigma_3_np, dtype=tf.complex64)

In [93]:
meas = [[1,1,0],[0,0,1]]
measurement = np.array(meas, dtype=np.complex64)
measurement_tensor = tf.Variable(measurement, tf.complex64)
print(measurement_tensor)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=complex64, numpy=
array([[1.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]], dtype=complex64)>


In [0]:
basis = tf.Variable([sigma_1,sigma_2,sigma_3])

In [99]:
density_matrix = 0.5*(sigma_0 + tf.tensordot(measurement_tensor,basis,axes=1))
print(density_matrix)

tf.Tensor(
[[[0.5+0.j  0.5+0.5j]
  [0.5-0.5j 0.5+0.j ]]

 [[1. +0.j  0. +0.j ]
  [0. +0.j  0. +0.j ]]], shape=(2, 2, 2), dtype=complex64)


In [108]:
tf.transpose(density_matrix, conjugate=True, perm=[0,2,1])

<tf.Tensor: shape=(2, 2, 2), dtype=complex64, numpy=
array([[[0.5-0.j , 0.5+0.5j],
        [0.5-0.5j, 0.5-0.j ]],

       [[1. -0.j , 0. -0.j ],
        [0. -0.j , 0. -0.j ]]], dtype=complex64)>

In [97]:
tf.linalg.trace(density_matrix)

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.+0.j, 1.+0.j], dtype=complex64)>

In [112]:
tf.reduce_sum(tf.linalg.eigh(density_matrix)[0], 0)

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.20710672+0.j,  2.2071066 +0.j], dtype=complex64)>

# Methods

In [116]:
def create_density_mat(measurements: np.array) -> tf.Tensor:
  
  #Creating the basis
  sigma_0_np = np.array([[1.,0.],
                        [0.,1.]], dtype=np.complex64)

  sigma_1_np = np.array([[0.,1.],
                         [1.,0.]], dtype=np.complex64)

  sigma_2_np = np.array([[0.,1.j],
                         [-1.j,0.]], dtype=np.complex64)

  sigma_3_np = np.array([[1.,0.],
                        [0.,-1.]], dtype=np.complex64)

  #Converting to tensors
  sigma_0 = tf.Variable(sigma_0_np, tf.complex64)

  sigma_1 = tf.Variable(sigma_1_np, tf.complex64)

  sigma_2 = tf.Variable(sigma_2_np, tf.complex64)

  sigma_3 = tf.Variable(sigma_3_np, dtype=tf.complex64)

  basis = tf.Variable([sigma_1,sigma_2,sigma_3])

  measurement = np.array(measurements, dtype=np.complex64)
  measurement_tensor = tf.Variable(measurement, tf.complex64)

  density_matrix = 0.5*(sigma_0 + tf.tensordot(measurement_tensor,basis,axes=1))
  return density_matrix

print(create_density_mat([[1,1,0],[0,0,1]]))

tf.Tensor(
[[[0.5+0.j  0.5+0.5j]
  [0.5-0.5j 0.5+0.j ]]

 [[1. +0.j  0. +0.j ]
  [0. +0.j  0. +0.j ]]], shape=(2, 2, 2), dtype=complex64)


In [113]:
def trace_dist(A,B):
  dif = A - B
  dif = tf.transpose(dif, conjugate=True, perm=[0,2,1]) * dif
  vals = tf.linalg.eigh(density_matrix)[0]
  return tf.math.real(0.5*tf.reduce_sum(tf.math.sqrt(tf.math.abs(vals)),0))

trace_dist(density_matrix, density_matrix)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.2275449, 1.049342 ], dtype=float32)>